export default {

    page_titles: {
        LOGO: "TalkToMedic",
        LOGIN: "Login",
        PATIENT_REGISTER: "Register As a Patient ",
        RMP_REGISTER: "Register As",
        PATIENT_PROFILE: "Edit Profile",
        PRACTICE_DETAIL: "Practice Details",
        ENTER_PHONE_NUMBER: "Phone Number",
        COUNTRY_SELECT: "Select Country",
        ACCOUNT: "Dashboard",
        FORGOT_PASSWORD: "Forgot Your Password? ",
        CHANGE_PASSWORD: "Change Password",
        ADD_MEMBER: "Family Member",
        CHOOSE_PROBLEM: "Add Family Member",
        APPOINTMENTS: "My Appointments",
        RMP_APPOINTMENTS: "My Appointments",
        CONSULTATION_FEE: "My Earnings",
        SETTING: "Checking Equipments",
        ENTER_PASSWORD: "Enter Password",
        CHOOSE_TREATMENT: "Search/Choose",
        CHOOSE_OPTION: "Choose Options",
        CANCEL_APPT: "Cancellation Reason",
        CHOOSE_APPT_TYPE: "Appointment Type",
        AVAILABLE_RMP: "Choose a Doctor",
        PAYMENT_RECEIPT: "Payment Receipt",
        MEDICAL_HISTORY: "Medical History",
        PRESCRIPTION: "Prescription",
        PHARMACY: "Share with Pharmacy",
        PHARMACY_OTP: "Verify Pharmacy",
        MANAGE_AVAILABLE: "Manage Availability",
        ADD_PRESCRIPTION: "Add/Edit Prescription",
        ADD_HISTORY: "Add Medical History",
        WITHDRAW: "Bank Details",
    },
    ROLE_PATIENT: "1",
    ROLE_RMP: 3,
    ROLE_WORKER: 2,
    ROLE_GIVER: 4,
    SET_COUNTRIES: 'SET_COUNTRY',
    SET_CITY: 'SET_CITY',
    SET_COUNCIL: 'SET_COUNCIL',
    SET_MEMBER: 'SET_MEMBER',
    SET_TREATMENT: 'SET_TREATMENT',
    SET_DEVICE_TOKEN: 'SET_DEVICE_TOKEN',
    SET_Voip_TOKEN: 'SET_Voip_TOKEN',
    SET_USER: "SET_USER",
    SET_USER_TYPE: "SET_USER_TYPE",
    SET_USER_DATA: "SET_USER_DATA",
    REMOVE_USER: "REMOVE_USER",
    SETLOCATION: "SETLOCATION",
    SET_OTP: "SET_OTP",
    SET_USER_REGISTER_FORM: "SET_USER_REGISTER_FORM",
    SET_PROBLEMS: "SET_PROBLEMS",
    SET_APPT_DATE_TIME: "SET_APPT_DATE_TIME",
    SET_APPT_TYPE: "SET_APPT_TYPE",
    SET_SPECIALITY: 'SET_SPECIALITY',
    SET_SESSION: "SET_SESSION",
    SET_RELATION: "SET_RELATION",
    SET_COMPLETENESS: 'SET_COMPLETENESS',
    SET_APPVERSION: "SET_APPVERSION",

    FAMILY_RELATIONS: [
        { name: "Father", id: "1" },
        { name: "Mother", id: "2" },
        { name: "Son", id: "3" },
        { name: "Daughter", id: "4" },
        { name: "Brother", id: "5" },
        { name: "Sister", id: "6" },
        { name: "Grandmother", id: "7" },
        { name: "Grandfather", id: "8" },
        { name: "Friend", id: "9" }],

    GENDER: ["Male", "Female", "Other"],

    CANCEL_REASON: ["Technical Problem", "Not Available", "Consult Not Required", "Other"],
    DOC_CANCEL_REASON: ["Technical Problem", "Busy Schedule", "Postpone Appointment", "Other"],
    DOCUMENT: ['PAN', 'VOTER ID', 'DRIVING LICENSE'],
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',

    slots: ["07:00 AM", "07:15 AM", "07:30 AM", "07:45 AM",
        "08:00 AM", "08:15 AM", "08:30 AM", "08:45 AM",
        "09:00 AM", "09:15 AM", "09:30 AM", "09:45 AM",
        "10:00 AM", "10:15 AM", "10:30 AM", "10:45 AM",
        "11:00 AM", "11:15 AM", "11:30 AM", "11:45 AM",
        "12:00 PM", "12:15 PM", "12:30 PM", "12:45 PM",
        "01:00 PM", "01:15 PM", "01:30 PM", "01:45 PM",
        "02:00 PM", "02:15 PM", "02:30 PM", "02:45 PM",
        "03:00 PM", "03:15 PM", "03:30 PM", "03:45 PM",
        "04:00 PM", "04:15 PM", "04:30 PM", "04:45 PM",
        "05:00 PM", "05:15 PM", "05:30 PM", "05:45 PM",
        "06:00 PM", "06:15 PM", "06:30 PM", "06:45 PM",
        "07:00 PM", "07:15 PM", "07:30 PM", "07:45 PM",
        "08:00 PM", "08:15 PM", "08:30 PM", "08:45 PM",
        "09:00 PM", "09:15 PM", "09:30 PM", "09:45 PM",
        "10:00 PM", "10:15 PM", "10:30 PM", "10:45 PM",
        "11:00 PM"],

    slots_obj: [{ time: "07:00 AM", is_selected: false }, { time: "07:15 AM", is_selected: false }, { time: "07:30 AM", is_selected: false }, { time: "07:45 AM", is_selected: false },
    { time: "08:00 AM", is_selected: true }, { time: "08:15 AM", is_selected: false }, { time: "08:30 AM", is_selected: false }, { time: "08:45 AM", is_selected: false },
    { time: "09:00 AM", is_selected: false }, { time: "09:15 AM", is_selected: false }, { time: "09:30 AM", is_selected: false }, { time: "09:45 AM", is_selected: false },
    { time: "10:00 AM", is_selected: false }, { time: "10:15 AM", is_selected: false }, { time: "10:30 AM", is_selected: false }, { time: "10:45 AM", is_selected: false },
    { time: "11:00 AM", is_selected: false }, { time: "11:15 AM", is_selected: false }, { time: "11:30 AM", is_selected: false }, { time: "11:45 AM", is_selected: false },
    { time: "12:00 PM", is_selected: false }, { time: "12:15 PM", is_selected: false }, { time: "12:30 PM", is_selected: false }, { time: "12:45 PM", is_selected: false },
    { time: "01:00 PM", is_selected: false }, { time: "01:15 PM", is_selected: false }, { time: "01:30 PM", is_selected: false }, { time: "01:45 PM" },
    { time: "02:00 PM", is_selected: false }, { time: "02:15 PM", is_selected: false }, { time: "02:30 PM", is_selected: false }, { time: "02:45 PM" },
    { time: "03:00 PM", is_selected: false }, { time: "03:15 PM", is_selected: false }, { time: "03:30 PM", is_selected: false }, { time: "03:45 PM" },
    { time: "04:00 PM", is_selected: false }, { time: "04:15 PM", is_selected: false }, { time: "04:30 PM", is_selected: false }, { time: "04:45 PM" },
    { time: "05:00 PM", is_selected: false }, { time: "05:15 PM", is_selected: false }, { time: "05:30 PM", is_selected: false }, { time: "05:45 PM", is_selected: false },
    { time: "06:00 PM", is_selected: false }, { time: "06:15 PM", is_selected: false }, { time: "06:30 PM", is_selected: false }, { time: "06:45 PM", is_selected: false },
    { time: "07:00 PM", is_selected: false }, { time: "07:15 PM", is_selected: false }, { time: "07:30 PM", is_selected: false }, { time: "07:45 PM", is_selected: false },
    { time: "08:00 PM", is_selected: false }, { time: "08:15 PM", is_selected: false }, { time: "08:30 PM", is_selected: false }, { time: "08:45 PM", is_selected: false },
    { time: "09:00 PM", is_selected: false }, { time: "09:15 PM", is_selected: false }, { time: "09:30 PM", is_selected: false }, { time: "09:45 PM", is_selected: false },
    { time: "10:00 PM", is_selected: false }, { time: "10:15 PM", is_selected: false }, { time: "10:30 PM", is_selected: false }, { time: "10:45 PM", is_selected: false },
    { time: "11:00 PM", is_selected: false }]

};